import { ArrowRight, CheckCircle2, LockKeyhole, Network, ShieldCheck, Sparkles } from "lucide-react";
import { signIn } from "@/auth";

export default function LoginPage() {
  return <main className="login-page">
    <section className="login-story"><div className="brand light"><span className="brand-mark"><span>H</span></span><span><strong>Hopper SE</strong><small>Automation Admin</small></span></div><div className="story-copy"><span className="kicker">AFFILIATE OPERATIONS</span><h1>One workspace.<br />Every channel in sync.</h1><p>Monitor account health, schedule partner engagement and audit every interaction from a single operations console.</p><ul><li><CheckCircle2 size={17} /> Health monitoring across three platforms</li><li><CheckCircle2 size={17} /> Timezone-aware automation schedules</li><li><CheckCircle2 size={17} /> Complete operational audit trail</li></ul></div><div className="orbit-visual"><span className="orbit core"><Sparkles size={22} /></span><span className="orbit node one">TK</span><span className="orbit node two">f</span><span className="orbit node three">▶</span></div><small className="story-foot">MKT-BOT · Built for responsible automation</small></section>
    <section className="login-form-area"><div className="login-card"><span className="login-icon"><Network size={25} /></span><span className="kicker">WELCOME BACK</span><h2>Đăng nhập hệ thống</h2><p>Sử dụng tài khoản Google Workspace của Hopper SE để tiếp tục.</p><form action={async () => {
      "use server";
      await signIn("google", { redirectTo: "/accounts" });
    }}><button className="google-button" type="submit"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.5h3.2c1.9-1.8 3-4.3 3-7.4Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 1-3.4 1a5.8 5.8 0 0 1-5.5-4H3.2v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.5 14a6 6 0 0 1 0-3.9V7.5H3.2a10 10 0 0 0 0 9.2L6.5 14Z"/><path fill="#EA4335" d="M12 6.1c1.5 0 2.8.5 3.8 1.5l2.9-2.8A9.7 9.7 0 0 0 3.2 7.5l3.3 2.6A5.8 5.8 0 0 1 12 6.1Z"/></svg>Continue with Google<ArrowRight size={17} /></button></form><div className="security-copy"><LockKeyhole size={15} /><span>SSO only. MKT-BOT never stores your Google password.</span></div></div><div className="login-trust"><ShieldCheck size={17} /><span>Restricted to <b>@hopper.capital</b> administrators</span></div></section>
  </main>;
}
